name: Deploy React Frontpage to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          npm i
          npm run build

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Prepare frontend directory on server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/web
            if [ -d "frontend-old" ]; then
              echo "Deleting old backup..."
              rm -rf frontend-old
            fi

            if [ -d "frontend" ]; then
              echo "Renaming frontend -> frontend-old..."
              mv frontend frontend-old
            fi

            mkdir frontend
            chmod -R 775 frontend
          EOF

      - name: Copy built files to server
        run: |
          scp -r build/* ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/web/frontend
