name: Deploy React Frontpage to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          npm i
          npm run build
        # Output goes to build/ as per vite.config.js

      - name: Test connectivity
        run: |
          echo "Pinging ${{ secrets.SERVER_IP }}…"
          ping -c 3 "${{ secrets.SERVER_IP }}" || true
          echo "Testing port 22…"
          nc -vz "${{ secrets.SERVER_IP }}" 22 || true

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts 2>/dev/null || true
          chmod 600 ~/.ssh/known_hosts

      - name: Prepare server deployment directory
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /home/ubuntu/web

            echo "Cleaning up previous backup if exists..."
            sudo rm -rf frontend-old

            if [ -d "frontend" ]; then
              echo "Renaming current frontend to frontend-old..."
              sudo mv frontend frontend-old
            fi

            echo "Creating new frontend directory..."
            mkdir frontend
          EOF

      - name: Copy built files to server
        run: |
          scp -r build/* \
            ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/web/frontend
