name: Deploy React Frontpage to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies & build
        run: |
          npm ci           # clean install
          npm run build    # outputs into build/

      - name: Test connectivity
        run: |
          echo "Pinging ${{ secrets.SERVER_IP }}…"
          ping -c 3 "${{ secrets.SERVER_IP }}" || true
          echo "Testing port 22…"
          nc -vz "${{ secrets.SERVER_IP }}" 22 || true

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Rotate old folders on server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            # 1) Remove the previous backup, if it exists
            if [ -d /home/ubuntu/web/frontend-old ]; then
              rm -rf /home/ubuntu/web/frontend-old
            fi

            # 2) Rename current live to backup
            if [ -d /home/ubuntu/web/frontend ]; then
              mv /home/ubuntu/web/frontend /home/ubuntu/web/frontend-old
            fi

            # 3) Re-create an empty live folder
            mkdir -p /home/ubuntu/web/frontend

            # 4) Ensure correct permissions so nginx (www-data) can read
            sudo chown -R www-data:www-data /home/ubuntu/web/
            sudo chmod -R 755 /home/ubuntu/web/frontend
          EOF

      - name: Copy built files to server
        run: |
          scp -r build/* \
            ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/web/frontend

